_wandb:
    value:
        cli_version: 0.23.0
        e:
            dy361ldodt1w6775yxb6s6cteb6gvina:
                args:
                    - --datasets
                    - indoor
                    - outdoor
                codePath: experiment.py
                codePathLocal: experiment.py
                cpu_count: 4
                cpu_count_logical: 4
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "40474304512"
                        used: "20715769856"
                email: 2025066613@QQ.com
                executable: /opt/anaconda3/bin/python3
                git:
                    commit: 842a2c25997ec445351895e4a4dd8f8c520db492
                    remote: git@github.com:EricluvPython/wireless-singal-synthesis.git
                gpu: NVIDIA A30-4C
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3584
                      memoryTotal: "4294967296"
                      name: NVIDIA A30-4C
                      uuid: GPU-b9ebfd53-33dc-11b2-819a-c3dffa2f8000
                host: nsl-gpu-n01
                memory:
                    total: "7789572096"
                os: Linux-6.8.0-87-generic-x86_64-with-glibc2.39
                program: /home/jingxia3/SeniorThesis/experiment.py
                python: CPython 3.10.9
                root: /home/jingxia3/SeniorThesis
                startedAt: "2025-11-23T21:54:43.396671Z"
                writerId: dy361ldodt1w6775yxb6s6cteb6gvina
        m: []
        python_version: 3.10.9
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 53
                - 105
            "3":
                - 1
                - 2
                - 3
                - 13
                - 16
            "4": 3.10.9
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
BATCH:
    value: 128
BETA_END:
    value: 0.02
BETA_START:
    value: 0.0001
CHANNELS:
    value: 1
CHECKPOINT_DIR:
    value: ./checkpoints
CHECKPOINT_EVERY:
    value: 100
DEPTH:
    value: 4
DROP:
    value: 0.1
EMA:
    value: true
EMA_DECAY:
    value: 0.999
GAN_HIDDEN:
    value: 128
GAN_LATENT_DIM:
    value: 100
GEN_EPOCHS:
    value: 2000
HEADS:
    value: 4
IMG_SIZE:
    value: 16
KEEP_LAST_N:
    value: 3
LR:
    value: 0.0002
MLP_EPOCHS:
    value: 100
MLP_HIDDEN:
    value: 256
MLP_LR:
    value: 0.002
PATCH:
    value: 4
SEED:
    value: 42
TIMESTEPS:
    value: 400
TRAIN_RATIOS:
    value:
        - 0.01
        - 0.05
        - 0.1
        - 0.25
        - 0.5
        - 0.8
        - 1
USE_WANDB:
    value: true
VEC_CLIP:
    value: 3
WANDB_ENTITY:
    value: null
WANDB_PROJECT:
    value: dit-data-fidelity
WIDTH:
    value: 256
WORKDIR:
    value: ./work_dir
